spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userbase?serverTimezone=Europe/Moscow&verifyServerCertificate=false&useSSL=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    database: default
vk:
  application-id:
  application-secret:
  access-token:
  api-version: 5.68 # vk api version

google:
  spreadsheetId:   # table id in Google
  tableName:  # list name of table (or can use Range like A1:E4)
  apiKey:  # secret API key from your google project

users:
  domainColumnNum: 0 #
  nameColumnNum: 1
  dateColumnNum: 2
  taskColumnNum: 3